### ISSUE TITLE
Steam can't see ED proton

### ISSUE THREAD

**Issue by neonrust** [redmcg/wine#1]
Steam does not seems to see my ED proton.

What shows up in  the "Compatibility tool" dropdown in Steam are (currently):

* Proton 3.16-4
* Proton 3.7-8-Beta
* Proton 3.7-8
* Proton 3.16-5

Am I correctly assuming that neither of those are correct?

Selecting 3.16-4 (it's at least the same version number...), it uses the shipped proton ( `~/.steam/steam/SteamApps/common/Proton 3.16`). Checked using `ps` after launching the game.

I tried both install locations:
`~/.steam/compatibilitytools.d/Proton 3.16-4 Beta ED`
and:
`~/.local/share/Steam/compatibilitytools.d/Proton\3.16-4 Beta ED`

Event tried making a symlink between those, so both of them exists. No show :(

Any ideas?

**Comment by redmcg** [comment]
You're right - none of these are the custom build - you should see it like this:
![steamplay](https://user-images.githubusercontent.com/8346438/50379396-eea58300-069c-11e9-87d4-f13e86445ab0.png)

Based on this:
`~/.steam/steam/SteamApps/common/Proton 3.16`

I'd say:
`~/.steam/compatibilitytools.d/Proton 3.16-4 Beta ED`
is the correct location.

If you've restarted Steam and it's still not showing up - then I'm not real sure.

**Comment by neonrust** [comment]
Thanks for your reply.  And yeah, I think the `~/.steam/` variant should be the correct one also.

I just tried the new release but still no show (also see 3.16-6 now, I guess it was just released?).
It's just as the screenshot above, but without the ED entry.

Hm... is there any way to get logs from steam? Running it in the terminal didn't say much...

**Comment by m1cr0man** [comment]
Hey. I had the same issue yesterday. I can at least say it certainly does not work in `~/.steam/compatibilitytools.d`, instead I had to put it into `~/.steam/steam/compatibilitytools.d` which at least on my system (SolusOS) is a symlink to `~/.local/share/Steam`. After restarting Steam it showed up as it does in the screenshot (and it worked flawlessly, by the way :smile: )

I did get a bit confused between the Steam version Lutris installed versus the system version, since it created 2 shortcuts. Also I copied the folder name `compatibilitytools.d` from your docs to make sure it was spelled correctly :stuck_out_tongue_winking_eye: 

In terms of logs, you should see a line in `~/.steam/steam/logs/compat_log.txt` which looks like this:

```
[2018-12-22 22:43:18] Processing local tool list at /home/$USER/.local/share/Steam/ubuntu12_32/../compatibilitytools.d/Proton 3.16-6 Beta ED/compatibilitytool.vdf...
[2018-12-22 22:43:18] Registering tool Proton 3.16-6 Beta ED, AppID 0
[2018-12-22 22:33:49] No local tool list detected at /home/$USER/.local/share/Steam/ubuntu12_32/../compatibilitytools.vdf.
```

**Comment by redmcg** [comment]
@m1cr0man Thanks for that information - I'll add it to my troubleshooting guide.
@tatsujin1 I guess you could run `ps ux | grep steam.sh` whilst steam is running to find the steam root location.

**Comment by neonrust** [comment]
@m1cr0man thanks for the log pointer. Indeed there's no mention of anything `compatibilitytools.d` in there...
I'll have to do some more digging I guess...

**Comment by redmcg** [comment]
I'll close this one. But please do re-open if you think you have found the issue and it's specifically related to this custom build of Proton.
