### ISSUE TITLE
EDLaunch says "unable to sync time" when started from Steam, manual start makes the game crash

### ISSUE THREAD

**Issue by s-iso** [redmcg/wine#3]
If anyone sees this issue after everything failed or checked the issues before blindly downloading things:
**You still need a KVM / native Windows to run Elite Dangerous. These fixes are not working at all yet.**

This is what happens if I run the game from steam directly:
![image](https://user-images.githubusercontent.com/6749862/50400430-ee81b200-0786-11e9-9c06-34bfd4e4b8a8.png)

This is what happens if I switch to Windows 7 (using winecfg on the Prefix):
![image](https://user-images.githubusercontent.com/6749862/50400251-841c4200-0785-11e9-8b76-5a2a71353149.png)

If I run it manually using this command (had to fiddle around with it for a long time to find this) with Windows 7, I can actually start the launcher but the game will get into a blackscreen for a long time and then error out (Frontier Error support showing up, I wrote some "friendly messages" to Frontier at that point due to frustration, sorry FDev but fuck you for showing us Linux folks the finger while gladly supporting each and every fucking console out there).

> WINESERVER="/home/r79/.local/share/Steam/compatibilitytools.d/Proton 3.16-5 Beta ED/proton" WINEPREFIX=/home/r79/.local/share/Steam/steamapps/compatdata/359320/pfx/ wine /home/r79/.steam/steam/steamapps/common/Elite\ Dangerous/EDLaunch.exe /EDH /steamid 441340 /novr 

I checked if dotnet40 and vcrun2015 were installed for multiple times, ran the installers atleast 10 times on that Prefix, completely uninstalled the game and deleted the prefix 3 times, to no prevail. I also tried it with dotnet45 and vcrun2017, which seems to be necessary for 3.3, but this also didn't work. This is not working. You still need a KVM to run Elite Dangerous.

**Comment by redmcg** [comment]
If you look here (the second image) - you'll see this user had the same issue:
https://forums.frontier.co.uk/showthread.php/366894-How-to-install-ED-on-Linux-using-Wine-EXPERIMENTAL-NOT-OFFICIALLY-SUPPORTED?p=7245372&viewfull=1#post7245372

And here the same user was able to get it working (by switching from Steam Beta Native to Steam Standard Runtime):
https://forums.frontier.co.uk/showthread.php/366894-How-to-install-ED-on-Linux-using-Wine-EXPERIMENTAL-NOT-OFFICIALLY-SUPPORTED?p=7246484&viewfull=1#post7246484

I think the Native Runtime vs Steam Runtime is a Solus option.

So the issue appears to be caused by a runtime library mismatch on gnutls (you're runtime library linker is not finding the Steam Runtime version that I compiled against). But unfortunately those errors you reported are Microsoft errors (from .NET) which are notorious for offering no information about the actual root cause. So a [log](https://github.com/ValveSoftware/Proton#runtime-config-options) will go a long way in helping to solve this issue.

Are you able to provide information about:
- which version of Proton you are using (and try the [latest](https://github.com/redmcg/wine/releases/tag/ED_Proton_3.16-6_Beta) if you haven't already);
- which distro you are using; and
- what graphics card and driver you are using

The reason I'm asking about graphics card and driver is because the blackscreen for a long time and then error out is often a DXVK/Vulkan issue. You could try with OpenGL to see if it makes a difference.

**Comment by s-iso** [comment]
Hey, I'm impressed by your quick update on the manner and your extended explanation.

I now also tried the following:
- Running it through Steam (Runtime) instead of Steam (Native)
- getting out of the Steam Beta and trying it again with Steam (Runtime)
- Running it in the console again with the aforementioned command to give you some logs (I created them with [command from above] 2>&1 | tee [outputfile]. I will try to give you Protonlogs in my next answer as well)

[ED_Proton_output.log](https://github.com/redmcg/wine/files/2707842/ED_Proton_output.log)


To answer your questions directly:
- I use Proton 3-16-5 provided by you. I'll try again with 3-16-6 now.
- I'm using Arch btw (sry couldn't resist)
- I'm using an NVidia GTX 980 with proprietary drivers (415.25-3). I never experienced any issues with DXVK nor Vulkan in general

Also: Merry Christmas and let me know if you want a Pizza donated ^-^

**Comment by s-iso** [comment]
UPDATE: Didn't work with the newer version either, unfortunate :disappointed: 
Also sorry for giving you the direct output, I realized that the logs produced by Proton are incredibly in-depth :sweat_smile:, so here we go with improved logs, yay.

Again, what I tried so far:
- running it with 3-16-6 from Steam (Runtime) (double checked that 3-16-6 is chosen).
Log: [can't upload because the file is actually 486.1 MB in size, but it actually looks more or less the same as the one below]

- ran it in the console again with the following command (everything the same as in the above example except for the WINESERVER path and the PROTON_LOG in the beginning)
> PROTON_LOG=1 WINESERVER="/home/r79/.local/share/Steam/compatibilitytools.d/Proton 3.16-6 Beta ED/proton" WINEPREFIX=/home/r79/.local/share/Steam/steamapps/compatdata/359320/pfx/ wine /home/r79/.steam/steam/steamapps/common/Elite\ Dangerous/EDLaunch.exe 2>&1 | tee slow/winestuff/ED_Proton_output.log
Log of that: 
[steam-359320.log](https://github.com/redmcg/wine/files/2707857/steam-359320.log)

Some other interesting observations I made:
- I believe proton doesn't launch correctly from Steam if I haven't done anything on the Prefix before hand (based on some dotnet errors I see that are telling me some things about some executable not being supported, will send you screens if interested).


**AAAAAND I MADE IT WORK!**
This is the godlike configuration that the random reader needs to make it work!
- Steam (Runtime), make sure you're not in Beta!
- use the newest version (duhhh)
- in case of stupidity (as in, for some reasons you broke the installation step which _I definitely did not do because I'm a good programmer_): you need dotnet40 and vcrun2015, in my personal case I actually used dotnet45 and vcrun2017
- THE WINE PREFIX MUST BE RUNNING ON WINDOWS 7

And with that, I wish you @redmcg a merry merry christmas and I wish myself some rehab after I went through multiple hours of one of my most favorite games ever :heart:

And I hereby close the issue, sorry for being stupid and bothering you on Christmas :S
