### ISSUE TITLE
error "Make sure you start the game from the launcher so that you are up to date"

### ISSUE THREAD

**Issue by regulator-g** [redmcg/wine#7]
Hi, When I launch ED the game opens but after planet generation I get the error "Make sure you start the game from the launcher so that you are up to date"

I have ran ./fixED.sh

On the page it says make sure vcrun2015 is installed, i have tried "winetricks vcrun2015" what do you mean install vcrun2015 in the ED prefix?

**Comment by redmcg** [comment]
A "wine prefix" is basically a new instance of windows (consisting of DLLs and registry settings). Proton will create a new "wine prefix" for every game it runs, so when you use winetricks - you need to set the environment variable `WINEPREFIX` to point to the ED wine prefix (which is created by Proton on first launch).

The location of the ED prefix will be <steam_install_loc>/steamapps/compatdata/359320/pfx where the steam_install_loc is the location you installed Elite Dangerous (as listed under Steam -> Settings -> Downloads -> STEAM LIBRARY FOLDERS).

So the command, for example, will be:
`WINEPREFIX=~/.steam/steam/steamapps/compatdata/359320/pfx winetricks vcrun2015 win7`

You'll want to put `win7` at the end as winetricks commonly switches the prefix to winxp to install things like vcrun and dotnet but ED needs it to be win7. The `win7` part will ensure it is set back to win7 after installing vcrun2015.

**Comment by regulator-g** [comment]
thanks for the info.. got a new issue now though. I run that command and I get "Unable to find the runtime to run this application" and then the VC installer pops up but says Another version is installed. Further to this when I try to launch ED the launcher windows does not popup "internal error creating window"

**Comment by redmcg** [comment]
The "Unable to find the runtime to run this application" is harmless. It occurs when you run a different version of wine against an already created prefix (Proton is using 3.16, your wine install [that winetricks is using] must be something different).

The VC installer saying that "Another version is installed" suggests that the previous attempt must have left traces of itself (but ultimately failed if you're seeing the error message in ED).

Finally the "internal error creating window" happens when the prefix is setup for winxp. This will be because after the vcrun2015 install failed, winetricks would have aborted, and not ran the win7 instruction (hence your prefix will still be configured for winxp). So that error message can be fixed by running `winetricks win7` (again with your `WINEPREFIX` set).

But then I suspect you will just get the error message in ED again. So I think the next thing to try is just deleting your prefix. This will cause a clean install of everything again.

To delete the prefix, just delete the folder. For example:
`rm -rf ~/.steam/steam/steamapps/compatdata/359320`

**Comment by regulator-g** [comment]
yep, deleting the folder and running the program again has sorted it out!

thanks heaps I was about to give up and install windows again

**Comment by redmcg** [comment]
Glad to hear. Thanks for reporting back.
